### ISSUE TITLE
ValueError: Unexpected capitalisation policy: 'inconsistent'

### ISSUE THREAD

**Issue by mrshu** [alanmcruickshank/sqlfluff#160]
Running version `0.2.4` (via the `sqlfluff lint` command) on the following file

```sql
SELECT COUNT(CustomerID), Country
FROM Customers
GROUP BY Country
HAVING COUNT(CustomerID) > 5;
```

results in the following stack trace

```
Traceback (most recent call last):
  File "/.venv-sqlfluff/bin/sqlfluff", line 11, in <module>
    load_entry_point('sqlfluff==0.2.4', 'console_scripts', 'sqlfluff')()
  File "/.venv-sqlfluff/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/.venv-sqlfluff/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/.venv-sqlfluff/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/.venv-sqlfluff/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/.venv-sqlfluff/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/.venv-sqlfluff/lib/python3.7/site-packages/sqlfluff/cli/commands.py", line 136, in lint
    result = lnt.lint_paths(paths, verbosity=verbose)
  File "/.venv-sqlfluff/lib/python3.7/site-packages/sqlfluff/linter.py", line 605, in lint_paths
    result.add(self.lint_path(path, verbosity=verbosity, fix=fix))
  File "/.venv-sqlfluff/lib/python3.7/site-packages/sqlfluff/linter.py", line 592, in lint_path
    fix=fix, config=config))
  File "/.venv-sqlfluff/lib/python3.7/site-packages/sqlfluff/linter.py", line 536, in lint_string
    lerrs, _, _, _ = crawler.crawl(parsed)
  File "/.venv-sqlfluff/lib/python3.7/site-packages/sqlfluff/rules/base.py", line 192, in crawl
    raw_stack=raw_stack, fix=fix, memory=memory)
  File "/.venv-sqlfluff/lib/python3.7/site-packages/sqlfluff/rules/base.py", line 192, in crawl
    raw_stack=raw_stack, fix=fix, memory=memory)
  File "/.venv-sqlfluff/lib/python3.7/site-packages/sqlfluff/rules/base.py", line 192, in crawl
    raw_stack=raw_stack, fix=fix, memory=memory)
  [Previous line repeated 3 more times]
  File "/.venv-sqlfluff/lib/python3.7/site-packages/sqlfluff/rules/base.py", line 162, in crawl
    raw_stack=raw_stack, memory=memory)
  File "/.venv-sqlfluff/lib/python3.7/site-packages/sqlfluff/rules/std.py", line 488, in _eval
    segment, self.capitalisation_policy))
  File "/.venv-sqlfluff/lib/python3.7/site-packages/sqlfluff/rules/std.py", line 463, in make_replacement
    return make_replacement(seg, list(cases_seen)[0])
  File "/.venv-sqlfluff/lib/python3.7/site-packages/sqlfluff/rules/std.py", line 469, in make_replacement
    raise ValueError("Unexpected capitalisation policy: {0!r}".format(policy))
ValueError: Unexpected capitalisation policy: 'inconsistent'
```

I am not sure whether this is related to #87  or #38, but I am happy to help with debugging this further (or trying out a fix).

Thanks again!

**Comment by mrshu** [comment]
This seems to be fixed on `master`. Sorry for the noise.
