### ISSUE TITLE
Bug: Doesn't handle 'do' expressions

### ISSUE THREAD

**Issue by r-hempenstall** [alanmcruickshank/sqlfluff#196]
Sqlfluff throws an error when my jinja macros contain `{%- do ... -%}` (https://jinja.palletsprojects.com/en/2.11.x/templates/#expression-statement). This is valid Jinja so I would expect not to.

```
Traceback (most recent call last):
  File "/usr/local/bin/sqlfluff", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/sqlfluff/cli/commands.py", line 145, in lint
    result = lnt.lint_paths(paths, verbosity=verbose)
  File "/usr/local/lib/python3.7/site-packages/sqlfluff/linter.py", line 681, in lint_paths
    result.add(self.lint_path(path, verbosity=verbosity, fix=fix))
  File "/usr/local/lib/python3.7/site-packages/sqlfluff/linter.py", line 668, in lint_path
    fix=fix, config=config))
  File "/usr/local/lib/python3.7/site-packages/sqlfluff/linter.py", line 535, in lint_string
    parsed, vs, time_dict = self.parse_string(s=s, fname=fname, verbosity=verbosity, config=config)
  File "/usr/local/lib/python3.7/site-packages/sqlfluff/linter.py", line 473, in parse_string
    s = self.templater.process(s, fname=fname, config=config or self.config)
  File "/usr/local/lib/python3.7/site-packages/sqlfluff/templaters.py", line 198, in process
    template = env.from_string(in_str)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 941, in from_string
    return cls.from_code(self, self.compile(source), globals, None)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 638, in compile
    self.handle_exception(source=source_hint)
  File "/usr/local/lib/python3.7/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.7/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<unknown>", line 26, in template
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'do'. Jinja was looking for the following tags: 'endmacro'. The innermost block that needs to be closed is 'macro'.
```

**Comment by alanmcruickshank** [comment]
Thanks @r-hempenstall , it looks like the `do` tag requires the explicit loading of an extension: https://jinja.palletsprojects.com/en/2.11.x/extensions/#expression-statement

Happy to do so, can you post a sample query here for me to include in the test suite?

**Comment by r-hempenstall** [comment]
Hey, I apologies, the query is quite contrived so that it doesn't require so much setup but this would be an example of it's use.
