### ISSUE TITLE
"sqlfluff fix" crash

### ISSUE THREAD

**Issue by barrywhart** [alanmcruickshank/sqlfluff#220]
This happens with SQLFluff 0.3.1.

Input:
```
select *
from  `{{project}}.{{dataset}}.user_labels_with_probs`
where prob_max >={{label_prob_threshold}}
--- only focus on 3 segments
and label_str not in ('marketing_maven', 'growth_services')
```

Result:
```
$ sqlfluff fix --dialect bigquery --rules L003,L006,L009 sql/user_stats/user_labels.sql
==== finding violations ====
== [sql/user_stats/user_labels.sql] FAIL
L:   3 | P:  18 | L006 | Operators should be followed by a space.
L:   4 | P:   1 | L003 | Indent expected and not found compared to line #1
L:   5 | P:  59 | L009 | Files must end with a trailing newline.
==== fixing violations ====
3 linting violations found
Are you sure you wish to attempt to fix these? [Y/n] ...
Attempting fixes...
Persisting Changes...
Traceback (most recent call last):
  File "/usr/local/pyenv/versions/3.7.3/bin/sqlfluff", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/pyenv/versions/3.7.3/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/pyenv/versions/3.7.3/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/pyenv/versions/3.7.3/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/pyenv/versions/3.7.3/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/pyenv/versions/3.7.3/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/pyenv/versions/3.7.3/lib/python3.7/site-packages/sqlfluff/cli/commands.py", line 228, in fix
    success = do_fixes(lnt, paths)
  File "/usr/local/pyenv/versions/3.7.3/lib/python3.7/site-packages/sqlfluff/cli/commands.py", line 158, in do_fixes
    res = result.persist_changes(output_func=lnt.output_func, **kwargs)
  File "/usr/local/pyenv/versions/3.7.3/lib/python3.7/site-packages/sqlfluff/linter.py", line 394, in persist_changes
    for path in self.paths
  File "/usr/local/pyenv/versions/3.7.3/lib/python3.7/site-packages/sqlfluff/linter.py", line 394, in <listcomp>
    for path in self.paths
  File "/usr/local/pyenv/versions/3.7.3/lib/python3.7/site-packages/sqlfluff/linter.py", line 304, in persist_changes
    buffer[file.path] = file.persist_tree(verbosity=verbosity)
  File "/usr/local/pyenv/versions/3.7.3/lib/python3.7/site-packages/sqlfluff/linter.py", line 241, in persist_tree
    write_buff, success = self.fix_string(verbosity=verbosity)
  File "/usr/local/pyenv/versions/3.7.3/lib/python3.7/site-packages/sqlfluff/linter.py", line 224, in fix_string
    "fix.").format(templ_block[0]))
ValueError: Unexpected opcode insert for template block! Please report this issue on github with the query and rules you're trying to fix.
```

Output:
```

```

**Comment by barrywhart** [comment]
`.sqlfluff`:
```
[sqlfluff]
verbose = 0
nocolor = False
dialect = bigquery
templater = jinja
rules = None
exclude_rules = None
recurse = 0

[sqlfluff:templater:jinja:macros]
# Macros provided as builtins for dbt projects
dbt_ref = {% macro ref(model_ref) %}{{model_ref}}{% endmacro %}
dbt_config = {% macro config() %}{% for k in kwargs %}{% endfor %}{% endmacro %}

# Some rules can be configured directly from the config common to other rules.
[sqlfluff:rules]
tab_space_size = 4

# Some rules have their own specific config.
[sqlfluff:rules:L010]
capitalisation_policy = consistent

[sqlfluff:rules:L016]
max_line_length = 100

[sqlfluff:templater:jinja:context]
gcp_project=marketing_segmentation
project=marketing_segmentation
dataset=dataset
orders_monthly_status=bi.bi_reporting.orders_monthly_status
users=bi.bi_reporting.users
benchmark=rsg-benchmarking-sum-prod.benchmarking_summary_2020_03_17.benchmark_user_map
vetting=bi.mailchimp.users_vetting
performance=rsg-benchmarking-sum-prod.benchmarking_summary_2020_03_17.campaign_performance
clv=mc-user-clv-prod-854440.mc_user_clv_scratch.clv_TEST_JOB_2020_03_15_2020_03_15_combined_results
apis=bi.bi_reporting.daily_api_requests
mobile=bi.bi_activities.mobile_activities
logins=bi.bi_reporting.daily_logins
label_prob_threshold=0.8
upsampling_user_labels=upsampling_user_labels
```
