### ISSUE TITLE
"sqlfluff lint" crashes if there are no files to process

### ISSUE THREAD

**Issue by barrywhart** [alanmcruickshank/sqlfluff#224]
Running this command with SQLFluff 0.3.1 when the `sql/` directory contains no `.sql` files:
```
sqlfluff lint --dialect bigquery sql/
```

results in this crash:
```
Traceback (most recent call last):

  File "/usr/local/pyenv/versions/lib-3.7.3/bin/sqlfluff", line 11, in <module>

    load_entry_point('sqlfluff==0.3.1', 'console_scripts', 'sqlfluff')()

  File "/usr/local/pyenv/versions/3.7.3/envs/lib-3.7.3/lib/python3.7/site-packages/click/core.py", line 829, in __call__

    return self.main(*args, **kwargs)

  File "/usr/local/pyenv/versions/3.7.3/envs/lib-3.7.3/lib/python3.7/site-packages/click/core.py", line 782, in main

    rv = self.invoke(ctx)

  File "/usr/local/pyenv/versions/3.7.3/envs/lib-3.7.3/lib/python3.7/site-packages/click/core.py", line 1259, in invoke

    return _process_result(sub_ctx.command.invoke(sub_ctx))

  File "/usr/local/pyenv/versions/3.7.3/envs/lib-3.7.3/lib/python3.7/site-packages/click/core.py", line 1066, in invoke

    return ctx.invoke(self.callback, **ctx.params)

  File "/usr/local/pyenv/versions/3.7.3/envs/lib-3.7.3/lib/python3.7/site-packages/click/core.py", line 610, in invoke

    return callback(*args, **kwargs)

  File "/usr/local/pyenv/versions/3.7.3/envs/lib-3.7.3/lib/python3.7/site-packages/sqlfluff/cli/commands.py", line 150, in lint

    lnt.log(format_linting_result_footer(result, verbose=verbose))

  File "/usr/local/pyenv/versions/3.7.3/envs/lib-3.7.3/lib/python3.7/site-packages/sqlfluff/cli/formatters.py", line 146, in format_linting_result_footer

    text_buffer.write(format_linting_stats(result, verbose=verbose))

  File "/usr/local/pyenv/versions/3.7.3/envs/lib-3.7.3/lib/python3.7/site-packages/sqlfluff/cli/formatters.py", line 106, in format_linting_stats

    all_stats = result.stats()

  File "/usr/local/pyenv/versions/3.7.3/envs/lib-3.7.3/lib/python3.7/site-packages/sqlfluff/linter.py", line 381, in stats

    all_stats['avg per file'] = all_stats['violations'] * 1.0 / all_stats['files']

ZeroDivisionError: float division by zero
```

**Comment by alanmcruickshank** [comment]
Right you are. PR coming up now. 👍

**Comment by barrywhart** [comment]
BTW, some of the data scientists like SQLFluff and have started asking me to add it to more projects. It's a lot more stable now, but with more projects, I'm still finding some issues. I'll try and log them here next week. I think most are just missing parts of the grammar. Happy to help out with these or other things.

I recently built an application that uses SQLFluff to parse production SQL and use it to automatically create data pipeline "lineage" diagrams similar to those in dbt but more detailed. The future possibilities are pretty exciting!
