### ISSUE TITLE
Bug: Issues with nested functions (e.g. SPLIT(LOWER(text), ' ') and so on)

### ISSUE THREAD

**Issue by mrshu** [alanmcruickshank/sqlfluff#23]
Consider the following query:

```sql
SELECT
    SPLIT(LOWER(text), ' ') AS text
FROM "database"."sample_table"
```

Saving this query to `b.sql` and running `sqlfluff lint -n b.sql` results in the following:

```
Traceback (most recent call last):
  File "/home/user/sql/.venv/bin/sqlfluff", line 11, in <module>
    load_entry_point('sqlfluff==0.1.3', 'console_scripts', 'sqlfluff')()
  File "/home/user/sql/.venv/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/user/sql/.venv/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/user/sql/.venv/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/user/sql/.venv/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/user/sql/.venv/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/user/sql/.venv/lib/python3.7/site-packages/sqlfluff/cli/commands.py", line 85, in lint
    result = lnt.lint_paths(paths, verbosity=verbose)
  File "/home/user/sql/.venv/lib/python3.7/site-packages/sqlfluff/linter.py", line 324, in lint_paths
    result.add(self.lint_path(path, verbosity=verbosity, fix=fix))
  File "/home/user/sql/.venv/lib/python3.7/site-packages/sqlfluff/linter.py", line 312, in lint_path
    linted_path.add(self.lint_file(f, fname=fname, verbosity=verbosity, fix=fix))
  File "/home/user/sql/.venv/lib/python3.7/site-packages/sqlfluff/linter.py", line 212, in lint_file
    parsed, vs, time_dict = self.parse_file(f=f, fname=fname, verbosity=verbosity)
  File "/home/user/sql/.venv/lib/python3.7/site-packages/sqlfluff/linter.py", line 193, in parse_file
    parsed = fs.parse(recurse=recurse, verbosity=verbosity, dialect=self.dialect)
  File "/home/user/sql/.venv/lib/python3.7/site-packages/sqlfluff/parser/segments_base.py", line 228, in parse
    verbosity=verbosity, dialect=dialect)
  File "/home/user/sql/.venv/lib/python3.7/site-packages/sqlfluff/parser/segments_base.py", line 394, in expand
    res = stmt.parse(recurse=recurse, parse_depth=parse_depth, verbosity=verbosity, dialect=dialect)
  File "/home/user/sql/.venv/lib/python3.7/site-packages/sqlfluff/parser/segments_base.py", line 228, in parse
    verbosity=verbosity, dialect=dialect)
  File "/home/user/sql/.venv/lib/python3.7/site-packages/sqlfluff/parser/segments_base.py", line 394, in expand
    res = stmt.parse(recurse=recurse, parse_depth=parse_depth, verbosity=verbosity, dialect=dialect)
  File "/home/user/sql/.venv/lib/python3.7/site-packages/sqlfluff/parser/segments_base.py", line 228, in parse
    verbosity=verbosity, dialect=dialect)
  File "/home/user/sql/.venv/lib/python3.7/site-packages/sqlfluff/parser/segments_base.py", line 394, in expand
    res = stmt.parse(recurse=recurse, parse_depth=parse_depth, verbosity=verbosity, dialect=dialect)
  File "/home/user/sql/.venv/lib/python3.7/site-packages/sqlfluff/parser/segments_base.py", line 228, in parse
    verbosity=verbosity, dialect=dialect)
  File "/home/user/sql/.venv/lib/python3.7/site-packages/sqlfluff/parser/segments_base.py", line 394, in expand
    res = stmt.parse(recurse=recurse, parse_depth=parse_depth, verbosity=verbosity, dialect=dialect)
  File "/home/user/sql/.venv/lib/python3.7/site-packages/sqlfluff/parser/segments_base.py", line 186, in parse
    dialect=dialect, match_segment=self.__class__.__name__)
  File "/home/user/sql/.venv/lib/python3.7/site-packages/sqlfluff/parser/grammar.py", line 70, in _match
    verbosity=verbosity, dialect=dialect, match_segment=match_segment)
  File "/home/user/sql/.venv/lib/python3.7/site-packages/sqlfluff/parser/grammar.py", line 273, in match
    verbosity=verbosity, dialect=dialect, match_segment=match_segment)
  File "/home/user/sql/.venv/lib/python3.7/site-packages/sqlfluff/parser/grammar.py", line 70, in _match
    verbosity=verbosity, dialect=dialect, match_segment=match_segment)
  File "/home/user/sql/.venv/lib/python3.7/site-packages/sqlfluff/parser/grammar.py", line 485, in match
    match_segment=match_segment)
  File "/home/user/sql/.venv/lib/python3.7/site-packages/sqlfluff/parser/grammar.py", line 70, in _match
    verbosity=verbosity, dialect=dialect, match_segment=match_segment)
  File "/home/user/sql/.venv/lib/python3.7/site-packages/sqlfluff/parser/grammar.py", line 273, in match
    verbosity=verbosity, dialect=dialect, match_segment=match_segment)
  File "/home/user/sql/.venv/lib/python3.7/site-packages/sqlfluff/parser/grammar.py", line 70, in _match
    verbosity=verbosity, dialect=dialect, match_segment=match_segment)
  File "/home/user/sql/.venv/lib/python3.7/site-packages/sqlfluff/parser/grammar.py", line 236, in match
    dialect=dialect, match_segment=match_segment)
  File "/home/user/sql/.venv/lib/python3.7/site-packages/sqlfluff/parser/segments_base.py", line 361, in _match
    verbosity=verbosity, dialect=dialect, match_segment=match_segment)
  File "/home/user/sql/.venv/lib/python3.7/site-packages/sqlfluff/parser/segments_base.py", line 320, in match
    dialect=dialect, match_segment=match_segment)
  File "/home/user/sql/.venv/lib/python3.7/site-packages/sqlfluff/parser/grammar.py", line 70, in _match
    verbosity=verbosity, dialect=dialect, match_segment=match_segment)
  File "/home/user/sql/.venv/lib/python3.7/site-packages/sqlfluff/parser/grammar.py", line 586, in match
    segment=segments[start_bracket_idx])
TypeError: tuple indices must be integers or slices, not NoneType
```

**Comment by alanmcruickshank** [comment]
Thanks @mrshu - I've confirmed this bug. Good catch. There's an issue with bracket counting which means it's trying to parse `SPLIT(LOWER(text)` and getting confused that it can't find the final bracket.

We don't have proper function parsing yet - but I'll add your example into the test suite and get it to pass. Thanks for posting such a clear example!

**Comment by alanmcruickshank** [comment]
More specifically on closer analysis, the `GreedyUntil` grammar doesn't yet implement bracket counting, so it finds the comma after `(text)` and just returns straight away. There's a hacky way of doing this but I'm going to have a think about how to make the bracket counting logic a bit more generic - because I've already implemented it in two separate other grammars.

**Comment by alanmcruickshank** [comment]
@mrshu - This is live in 0.2.1 now. Can you see if  you're able to upgrade from <0.1 up to 0.2 now?

**Comment by mrshu** [comment]
Thanks @alanmcruickshank -- the `0.2` upgrade does seem to resolve this, although there a few other issues I've ran into (I've tried to document them in the issue tracker here).
