### ISSUE TITLE
Bump version of required click module

### ISSUE THREAD

**Issue by dr-1** [alanmcruickshank/sqlfluff#241]
requirements.txt currently lists click>=2.0. With sqlfluff 0.3.1 and click 6.7 installed, any sqlfluff CLI command fails for me with this error.
```
Traceback (most recent call last):
  File "/home/dominikr/.local/bin/sqlfluff", line 11, in <module>
    load_entry_point('sqlfluff==0.3.1', 'console_scripts', 'sqlfluff')()
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 2728, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 2346, in load
    return self.resolve()
  File "/usr/local/lib/python3.7/dist-packages/pkg_resources/__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/dominikr/.local/lib/python3.7/site-packages/sqlfluff/cli/commands.py", line 248, in <module>
    type=click.Choice(['human', 'yaml'], case_sensitive=False),
TypeError: __init__() got an unexpected keyword argument 'case_sensitive'
```
Upgrading to click 7.1.1 resolved the error for me.

**Comment by alanmcruickshank** [comment]
Thanks for the heads up!
