### ISSUE TITLE
RuntimeError: Unexpected case, please report bug, inluding the query you are linting!

### ISSUE THREAD

**Issue by Katzmann1983** [alanmcruickshank/sqlfluff#263]
On the latest master, the following sql cannot be fixed:
echo -e "SELECT\nCASE\n     WHEN (a < 0) THEN 2\n     ELSE -- comment\n         0 END\nFROM t1" > sample.sql

sqlfluff fix --rules L003 sample.sql

==== finding violations ====
== [runtime_error.sql] FAIL
L:   2 | P:   1 | L003 | Indent expected and not found compared to line #1
L:   3 | P:   6 | L003 | Indentation not hanging or a multiple of 4 spaces
L:   4 | P:   6 | L003 | Indentation not hanging or a multiple of 4 spaces
L:   5 | P:  10 | L003 | Indentation not hanging or a multiple of 4 spaces
==== fixing violations ====
4 linting violations found
Are you sure you wish to attempt to fix these? [Y/n] ...
Attempting fixes...
Traceback (most recent call last):
  File "/anaconda3/bin/sqlfluff", line 11, in <module>
    load_entry_point('sqlfluff==0.3.1', 'console_scripts', 'sqlfluff')()
  File "/anaconda3/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/anaconda3/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/anaconda3/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/anaconda3/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/anaconda3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/anaconda3/lib/python3.7/site-packages/sqlfluff-0.3.1-py3.7.egg/sqlfluff/cli/commands.py", line 245, in fix
    success = do_fixes(lnt, paths)
  File "/anaconda3/lib/python3.7/site-packages/sqlfluff-0.3.1-py3.7.egg/sqlfluff/cli/commands.py", line 173, in do_fixes
    result = lnt.lint_paths(paths, fix=True)
  File "/anaconda3/lib/python3.7/site-packages/sqlfluff-0.3.1-py3.7.egg/sqlfluff/linter.py", line 760, in lint_paths
    result.add(self.lint_path(path, verbosity=verbosity, fix=fix))
  File "/anaconda3/lib/python3.7/site-packages/sqlfluff-0.3.1-py3.7.egg/sqlfluff/linter.py", line 747, in lint_path
    fix=fix, config=config))
  File "/anaconda3/lib/python3.7/site-packages/sqlfluff-0.3.1-py3.7.egg/sqlfluff/linter.py", line 653, in lint_string
    lerrs, _, fixes, _ = crawler.crawl(working, fix=True)
  File "/anaconda3/lib/python3.7/site-packages/sqlfluff-0.3.1-py3.7.egg/sqlfluff/rules/base.py", line 216, in crawl
    raw_stack=raw_stack, fix=fix, memory=memory)
  File "/anaconda3/lib/python3.7/site-packages/sqlfluff-0.3.1-py3.7.egg/sqlfluff/rules/base.py", line 216, in crawl
    raw_stack=raw_stack, fix=fix, memory=memory)
  File "/anaconda3/lib/python3.7/site-packages/sqlfluff-0.3.1-py3.7.egg/sqlfluff/rules/base.py", line 216, in crawl
    raw_stack=raw_stack, fix=fix, memory=memory)
  [Previous line repeated 5 more times]
  File "/anaconda3/lib/python3.7/site-packages/sqlfluff-0.3.1-py3.7.egg/sqlfluff/rules/base.py", line 186, in crawl
    raw_stack=raw_stack, memory=memory)
  File "/anaconda3/lib/python3.7/site-packages/sqlfluff-0.3.1-py3.7.egg/sqlfluff/rules/std.py", line 433, in _eval
    raise RuntimeError("Unexpected case, please report bug, inluding the query you are linting!")
RuntimeError: Unexpected case, please report bug, inluding the query you are linting!

**Comment by alanmcruickshank** [comment]
Thanks for the bug report. It's due to there being a comment at the line 4, PR coming to address that case.
