### ISSUE TITLE
"sqlfluff lint" crashes on this parse error

### ISSUE THREAD

**Issue by barrywhart** [alanmcruickshank/sqlfluff#313]
Input:
```
SELECT
    user_id,
    list_id,
    COUNT(email_id) AS audience
FROM
    `bi.user.lists_emails` AS list_emails
    FOR SYSTEM_TIME AS OF CAST('2020-05-11T14:02:52+00:00' AS TIMESTAMP
```

(Note the grammatical error: There is a missing `)` at the end of the query.)

Output:
```
sqlfluff lint --dialect bigquery datascience-benchmark-summary/test.sql
Linting file datascience-benchmark-summary/test.sql
Traceback (most recent call last):
  File "/Users/bhart/.pyenv/versions/sqlfluff-3.6.4/bin/sqlfluff", line 11, in <module>
    load_entry_point('sqlfluff', 'console_scripts', 'sqlfluff')()
  File "/Users/bhart/.pyenv/versions/3.6.4/envs/sqlfluff-3.6.4/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/bhart/.pyenv/versions/3.6.4/envs/sqlfluff-3.6.4/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/bhart/.pyenv/versions/3.6.4/envs/sqlfluff-3.6.4/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/bhart/.pyenv/versions/3.6.4/envs/sqlfluff-3.6.4/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/bhart/.pyenv/versions/3.6.4/envs/sqlfluff-3.6.4/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/bhart/dev/sqlfluff/src/sqlfluff/cli/commands.py", line 162, in lint
    result = lnt.lint_paths(paths, verbosity=verbose, ignore_non_existent_files=False)
  File "/Users/bhart/dev/sqlfluff/src/sqlfluff/linter.py", line 892, in lint_paths
    ignore_non_existent_files=ignore_non_existent_files))
  File "/Users/bhart/dev/sqlfluff/src/sqlfluff/linter.py", line 878, in lint_path
    fix=fix, config=config))
  File "/Users/bhart/dev/sqlfluff/src/sqlfluff/linter.py", line 692, in lint_string
    parsed, vs, time_dict = self.parse_string(s=s, fname=fname, verbosity=verbosity, config=config)
  File "/Users/bhart/dev/sqlfluff/src/sqlfluff/linter.py", line 634, in parse_string
    for unparsable in parsed.iter_unparsables():
AttributeError: 'NoneType' object has no attribute 'iter_unparsables'
```

**Comment by alanmcruickshank** [comment]
Good catch, fix coming shortly.
