### ISSUE TITLE
Sqlfluff should give a more helpful error message when run in python 2.

### ISSUE THREAD

**Issue by zvikorn** [alanmcruickshank/sqlfluff#370]
sqlfluff lint test.sql
Traceback (most recent call last):
  File "/usr/bin/sqlfluff", line 11, in <module>
    load_entry_point('sqlfluff==0.3.1', 'console_scripts', 'sqlfluff')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2411, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2417, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/sqlfluff/cli/commands.py", line 7, in <module>
    from ..dialects import dialect_selector
  File "/usr/lib/python2.7/site-packages/sqlfluff/dialects/__init__.py", line 4, in <module>
    from .dialect_ansi import ansi_dialect
  File "/usr/lib/python2.7/site-packages/sqlfluff/dialects/dialect_ansi.py", line 15, in <module>
    from ..parser import (BaseSegment, KeywordSegment, ReSegment, NamedSegment,
  File "/usr/lib/python2.7/site-packages/sqlfluff/parser/__init__.py", line 11, in <module>
    from .segments_file import FileSegment
  File "/usr/lib/python2.7/site-packages/sqlfluff/parser/segments_file.py", line 9, in <module>
    class FileSegment(BaseSegment):
  File "/usr/lib/python2.7/site-packages/sqlfluff/parser/segments_file.py", line 21, in FileSegment
    allow_trailing=True
  File "/usr/lib/python2.7/site-packages/sqlfluff/parser/grammar.py", line 796, in __init__
    super(Delimited, self).__init__(*args, **kwargs)
TypeError: super() argument 1 must be type, not classobj

**Comment by alanmcruickshank** [comment]
Thanks @zvikorn . Looks like you're running on python 2.7. Support for that distribution was dropped when we moved to version 0.3.0 of python. You'll still be able to use earlier versions of sqlfluff before 0.3.0, but a lot of the more recently functionality won't be in there.

Unless you have a compelling reason to use python 2.7, I'd highly recommend upgrading to one of the more recent releases of python 3. You can read about the reasons for doing that here: https://stxnext.com/blog/2019/07/30/why-migrate-from-python-2-to-python-3/

All that being said - that error message isn't very helpful. I'll see if we can add something in there to flag that the version of python you'r using isn't supported.
