### ISSUE TITLE
[dbt] Tuple index out of range when there is a configuration block

### ISSUE THREAD

**Issue by flpezet** [alanmcruickshank/sqlfluff#376]
With dbt, it is possible to change configuration directly in the SQL query.(https://docs.getdbt.com/reference/model-configs#configuring-models)

The following query:
```
{{ config(materialized="table") }}

select
    a
from my_table
```
results into...

```
Traceback (most recent call last):
  File "//miniconda3/envs/pipelines_dbt/bin/sqlfluff", line 10, in <module>
    sys.exit(cli())
  File "//miniconda3/envs/pipelines_dbt/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "//miniconda3/envs/pipelines_dbt/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "//miniconda3/envs/pipelines_dbt/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "//miniconda3/envs/pipelines_dbt/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "//miniconda3/envs/pipelines_dbt/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "//miniconda3/envs/pipelines_dbt/lib/python3.7/site-packages/sqlfluff/cli/commands.py", line 162, in lint
    result = lnt.lint_paths(paths, verbosity=verbose, ignore_non_existent_files=False)
  File "//miniconda3/envs/pipelines_dbt/lib/python3.7/site-packages/sqlfluff/linter.py", line 891, in lint_paths
    ignore_non_existent_files=ignore_non_existent_files))
  File "//miniconda3/envs/pipelines_dbt/lib/python3.7/site-packages/sqlfluff/linter.py", line 877, in lint_path
    fix=fix, config=config))
  File "//miniconda3/envs/pipelines_dbt/lib/python3.7/site-packages/sqlfluff/linter.py", line 727, in lint_string
    lerrs, _, _, _ = crawler.crawl(parsed, dialect=config.get('dialect_obj'))
  File "//miniconda3/envs/pipelines_dbt/lib/python3.7/site-packages/sqlfluff/rules/base.py", line 264, in crawl
    dialect=dialect)
  File "//miniconda3/envs/pipelines_dbt/lib/python3.7/site-packages/sqlfluff/rules/base.py", line 217, in crawl
    raw_stack=raw_stack, memory=memory, dialect=dialect)
  File "//miniconda3/envs/pipelines_dbt/lib/python3.7/site-packages/sqlfluff/rules/std.py", line 27, in _eval
    if raw_stack[idx].type == 'whitespace':
IndexError: tuple index out of range
```

**Comment by alanmcruickshank** [comment]
Strange. I can't recreate this error. Can you post your config and version that you're running to get this error?

**Comment by flpezet** [comment]
After re-installing sqlfluff it worked fine. I'm closing this issue.

**Comment by MinchoG** [comment]
I am currently using latest stable version and I have this error. After reinstalling it is not working for me. After I run:
`sqlfluff lint models/5_WAREHOUSE/F_MIXPANEL_EVENTS.sql `
I get the following errors:
```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/sqlfluff", line 8, in <module>
    sys.exit(cli())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sqlfluff/cli/commands.py", line 172, in lint
    result = lnt.lint_paths(paths, verbosity=verbose, ignore_non_existent_files=False)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sqlfluff/linter.py", line 911, in lint_paths
    result.add(self.lint_path(path, verbosity=verbosity, fix=fix,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sqlfluff/linter.py", line 896, in lint_path
    self.lint_string(target_file.read(), fname=fname,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sqlfluff/linter.py", line 748, in lint_string
    lerrs, _, _, _ = crawler.crawl(parsed, dialect=config.get('dialect_obj'))
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sqlfluff/rules/base.py", line 268, in crawl
    dvs, raw_stack, child_fixes, memory = self.crawl(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sqlfluff/rules/base.py", line 233, in crawl
    res = self._eval(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/sqlfluff/rules/std.py", line 53, in _eval
    if raw_stack[idx].type == 'whitespace':
IndexError: tuple index out of range
```

**Comment by joaoheron** [comment]
I'm facing this same issue.

**Comment by joaoheron** [comment]
I'm facing this same issue, but only on Bitbucket Pipelines environment. Local execution works fine.

**Comment by joaoheron** [comment]
Just find a workaround. Install sqlfluff without aiming for a specific version. Simply `pip install  sqlfluff ` and it will do.

**Comment by MinchoG** [comment]
I disagree, it does not work with me, I will open an issue

**Comment by joaoheron** [comment]
@MinchoG also you must be sure that your pip version is up to date. 
`pip install -U pip`

**Comment by MinchoG** [comment]
pip install -U pip
Requirement already satisfied: pip in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages (20.3.3)

**Comment by MinchoG** [comment]
https://github.com/sqlfluff/sqlfluff/issues/668

**Comment by drewmcdonald** [comment]
Also #661.
