### ISSUE TITLE
Bug: SQLFluff needs to include jinja2 in its "install_requires" list in setup.py

### ISSUE THREAD

**Issue by barrywhart** [alanmcruickshank/sqlfluff#79]
Without this, if I `pip install sqlfluff` and run it, I get an error, e.g.:

```
$ sqlfluff lint test.sql
SELECT
Traceback (most recent call last):
  File "/Users/bhart/.pyenv/versions/sqlfluff-prod-3.6.4/bin/sqlfluff", line 11, in <module>
SELECT
    load_entry_point('sqlfluff==0.2.3', 'console_scripts', 'sqlfluff')()
  File "/Users/bhart/.pyenv/versions/3.6.4/envs/sqlfluff-prod-3.6.4/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/bhart/.pyenv/versions/3.6.4/envs/sqlfluff-prod-3.6.4/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/bhart/.pyenv/versions/3.6.4/envs/sqlfluff-prod-3.6.4/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/bhart/.pyenv/versions/3.6.4/envs/sqlfluff-prod-3.6.4/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/bhart/.pyenv/versions/3.6.4/envs/sqlfluff-prod-3.6.4/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/bhart/.pyenv/versions/3.6.4/envs/sqlfluff-prod-3.6.4/lib/python3.6/site-packages/sqlfluff/cli/commands.py", line 139, in lint
    result = lnt.lint_paths(paths, verbosity=verbose)
  File "/Users/bhart/.pyenv/versions/3.6.4/envs/sqlfluff-prod-3.6.4/lib/python3.6/site-packages/sqlfluff/linter.py", line 589, in lint_paths
    result.add(self.lint_path(path, verbosity=verbosity, fix=fix))
  File "/Users/bhart/.pyenv/versions/3.6.4/envs/sqlfluff-prod-3.6.4/lib/python3.6/site-packages/sqlfluff/linter.py", line 576, in lint_path
    linted_path.add(self.lint_string(f.read(), fname=fname, verbosity=verbosity, fix=fix, config=config))
  File "/Users/bhart/.pyenv/versions/3.6.4/envs/sqlfluff-prod-3.6.4/lib/python3.6/site-packages/sqlfluff/linter.py", line 452, in lint_string
    parsed, vs, time_dict = self.parse_string(s=s, fname=fname, verbosity=verbosity, config=config)
  File "/Users/bhart/.pyenv/versions/3.6.4/envs/sqlfluff-prod-3.6.4/lib/python3.6/site-packages/sqlfluff/linter.py", line 392, in parse_string
    s = self.templater.process(s, fname=fname, config=config or self.config)
  File "/Users/bhart/.pyenv/versions/3.6.4/envs/sqlfluff-prod-3.6.4/lib/python3.6/site-packages/sqlfluff/templaters.py", line 178, in process
    from jinja2 import Environment, StrictUndefined  # noqa
ModuleNotFoundError: No module named 'jinja2'
```

**Comment by alanmcruickshank** [comment]
Good catch. This will be in the next release.
